import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:split_bill/auth/register_screen.dart';
import 'package:split_bill/screen/home.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:split_bill/auth/loginScreen.dart';
import 'package:firebase_auth/firebase_auth.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await FirebaseAuth.instance.useAuthEmulator('192.168.1.12', 9099);

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Auth Demo',
      initialRoute: "/",
      routes: {
        "/": (context) => LoginScreen(),
        "/register": (context) => RegisterScreen(),
        "/home": (context) => Home(),
      },
    );
  }
}
